// One empty spare room, staged three times as three different uses.
//
// The point of the post is that the FUNCTION changes while the room stays the same, so all
// three renders have to come from a single source photograph. acquirePair sources and
// stages in one call, which would give three different rooms, so this reproduces its
// source-retry logic by hand: acquire one "before", stage it three ways, and only fall
// through to a different source photo if the first render comes back badly.
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createStagifyImages } from '../../../lib/images/stagify.js';
import { createFalClient } from '../../../lib/images/fal.js';
import { createStockSource } from '../../../lib/images/stock.js';
import { createAcquire, sha256 } from '../../../lib/images/acquire.js';
import { loadConfig } from '../../../lib/history/store.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const HERE = path.dirname(fileURLToPath(import.meta.url));

const config = loadConfig(REPO_ROOT);
const stagify = createStagifyImages({ config });
const fal = createFalClient();
const stock = createStockSource({ config });
const acquire = createAcquire({ config, repoRoot: REPO_ROOT, stagify, stock, fal });

const QUERY = 'empty unfurnished spare bedroom small room white walls window daylight';
const PROMPT = 'A photorealistic estate agent photograph of a completely empty, unfurnished small '
  + 'spare room. Bare pale wood floor, blank white walls, one window on the left wall with '
  + 'daylight, a plain white door on the right, no furniture, no rugs, no artwork, no people. '
  + 'Shot straight on with a wide lens at chest height, neutral white balance, sharp focus '
  + 'throughout.';

// Same style across all three on purpose. If the style changed too, the post would be about
// taste rather than about what the room is for.
const USES = [
  {
    key: 'office',
    roomType: 'Office',
    style: 'scandinavian',
    additionalPrompt: 'Furnish as a working home office: a slim desk against the window wall, '
      + 'a low shelf and a plant. The chair must be a plain wooden dining style chair with '
      + 'exactly four straight tapered legs, no wheels, no castors, no swivel base and no gas '
      + 'lift column, and all four feet must sit flat on the floor with a visible contact '
      + 'shadow. No desk lamp and no monitor. Keep the floor, walls, window and door exactly '
      + 'as photographed.',
  },
  {
    key: 'guest',
    roomType: 'Bedroom',
    style: 'scandinavian',
    additionalPrompt: 'Furnish as a guest bedroom: one neatly made double bed against the far '
      + 'wall and a folded throw across it. Two bedside tables that are identical to each '
      + 'other in height and shape, each with an identical lamp, each with exactly four legs '
      + 'standing flat on the floor. No clock, no armchair, no other seating anywhere in the '
      + 'room. Keep the floor, walls, window and door exactly as photographed.',
  },
  {
    key: 'sitting',
    roomType: 'Living room',
    style: 'scandinavian',
    additionalPrompt: 'Furnish as a quiet reading room: one armchair by the window, a low '
      + 'bookshelf against the far wall and a small round side table. The armchair must have '
      + 'exactly four straight tapered wooden legs, every one of them reaching the floor and '
      + 'casting a contact shadow. Nothing resting on the armchair. No mug, no cup, no steam, '
      + 'no smoke, no vapour anywhere in the room. No footstool, no floor lamp, no sofa, no '
      + 'television. Keep the floor, walls, window and door exactly as photographed.',
  },
];

// Round two of the image review re-stages to fix chair legs, so the source photograph is
// pinned rather than re-acquired. A different empty room would invalidate the review that
// already confirmed slides two to four are the same room to within a pixel or two.
const PINNED_BEFORE = process.env.PINNED_BEFORE
  ? path.join(REPO_ROOT, 'instagram', 'assets', 'sources', process.env.PINNED_BEFORE)
  : null;

const tried = new Set();
let winner = null;

for (let attempt = 1; attempt <= (PINNED_BEFORE ? 1 : 2); attempt += 1) {
  console.log(`\n=== source photo attempt ${attempt} ===`);
  const sourced = PINNED_BEFORE
    ? {
      buffer: fs.readFileSync(PINNED_BEFORE),
      mime: 'image/jpeg',
      origin: 'fal',
      license: {
        type: 'generated',
        licenseName: 'Generated by fal.ai, no third-party rights',
        attributionRequired: false,
        model: 'fal-ai/flux/dev',
      },
    }
    : await acquire.acquireBefore({
      query: QUERY, prompt: PROMPT, orientation: 'portrait', usedHashes: tried,
    });
  console.log(`  before: ${sourced.origin}${PINNED_BEFORE ? ' (pinned)' : ''}`);

  const renders = [];
  for (const use of USES) {
    console.log(`  staging ${use.key} (${use.roomType}) ...`);
    const staged = await stagify.stage({
      sourceBuffer: sourced.buffer,
      roomType: use.roomType,
      furnitureStyle: use.style,
      additionalPrompt: use.additionalPrompt,
      removeFurniture: false,
      labelVirtuallyStaged: false,
    });
    console.log(`    perfect=${staged.quality.perfect} score=${staged.quality.bestScore}`);
    renders.push({ use, staged });
  }

  const worst = Math.min(...renders.map((r) => r.staged.quality.bestScore ?? 0));
  const allPerfect = renders.every((r) => r.staged.quality.perfect);
  const candidate = { sourced, renders, worst, allPerfect };
  console.log(`  worst score across the three: ${worst}`);

  if (!winner || worst > winner.worst) winner = candidate;
  if (allPerfect) break;
  tried.add(sha256(sourced.buffer));
}

const before = await acquire.store(winner.sourced.buffer, winner.sourced.mime);
const out = { before: { ...before, origin: winner.sourced.origin, license: winner.sourced.license }, renders: [] };

for (const { use, staged } of winner.renders) {
  const stored = await acquire.store(staged.buffer, staged.mime);
  out.renders.push({
    key: use.key,
    roomType: use.roomType,
    style: use.style,
    additionalPrompt: use.additionalPrompt,
    ...stored,
    model: staged.model,
    params: staged.params,
    quality: staged.quality,
  });
}

fs.writeFileSync(path.join(HERE, 'images.json'), `${JSON.stringify(out, null, 2)}\n`);
console.log('\nWrote work/images.json');
console.log(`  before  ${out.before.url}`);
for (const r of out.renders) {
  console.log(`  ${r.key.padEnd(8)} ${r.url}  perfect=${r.quality.perfect} score=${r.quality.bestScore}`);
  if (!r.quality.perfect) {
    for (const d of [...new Set(r.quality.defects ?? [])]) {
      console.log(`      flagged: ${d.replace(/\s+/g, ' ').trim().slice(0, 150)}`);
    }
  }
}
