// Prompt matrix for room type and furniture style combinations
export const promptMatrix = {
  'Bedroom': {
    'standard': "Stage this bedroom with stylish, contemporary furniture that appeals to a broad audience. Add a modern bed with clean lines, matching nightstands with table lamps, a dresser with mirror, soft neutral bedding with throw pillows, a cozy armchair or bench, and wall art. Use neutral colors and clean lines throughout.",
    'modern': "Stage this bedroom in a modern style with a low-profile platform bed in neutral tones, sleek nightstands with minimalist table lamps, a contemporary dresser with modern hardware, luxury bedding with geometric throw pillows, a sculptural accent chair, modern wall art, and statement lighting. Add a large area rug and keep accessories minimal with clean, geometric designs.",
    'midcentury': "Stage this bedroom with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage-inspired bed frame, matching nightstands with retro lamps, a teak dresser, mid-century bedding with bold patterns, an Eames-style chair, vintage wall art, and geometric lighting fixtures.",
    'scandinavian': "Stage this bedroom in Scandinavian style with light wood furniture, neutral textiles, cozy textures, and minimalist décor. Add a simple bed frame, wooden nightstands, a minimalist dresser, soft white bedding with knit throws, a cozy reading chair, natural wood accessories, and simple wall art. Focus on functionality, hygge comfort, and natural materials.",
    'luxury': "Stage this bedroom with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add an upholstered headboard, marble-topped nightstands with crystal lamps, a luxury dresser with gold hardware, silk bedding with velvet throw pillows, a tufted accent chair, ornate mirrors, and elegant wall art. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this bedroom with coastal-inspired furniture in light blues, whites, and natural textures. Add a white or light wood bed frame, wicker nightstands, a distressed dresser, nautical bedding with striped throw pillows, a rattan chair, seashell accessories, ocean-themed wall art, and natural lighting. Create an airy, relaxed styling.",
    'farmhouse': "Stage this bedroom with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a wooden bed frame, vintage nightstands with mason jar lamps, a distressed dresser, floral bedding with quilted throws, a rocking chair, vintage accessories, and country-style wall art. Create a charming, country-inspired atmosphere.",
    'custom': "Stage this bedroom with the furniture and decor the user asks for."
  },
  'Living room': {
    'standard': "Stage this living room with stylish, contemporary furniture that appeals to a broad audience. Add a comfortable sofa with throw pillows, a coffee table with decorative items, an entertainment center or TV stand, accent chairs, side tables with table lamps, an area rug, wall art, and plants. Use neutral colors and clean lines.",
    'modern': "Stage this living room in a modern style by adding a low-profile sectional sofa in neutral colors with geometric throw pillows, a sleek glass or polished stone coffee table with minimalist decor, an accent chair with bold sculptural design, modern side tables with contemporary lamps, a large area rug, abstract wall art, and statement lighting fixtures.",
    'midcentury': "Stage this living room with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage sofa with colorful throw pillows, a teak coffee table, Eames-style chairs, retro side tables with atomic lamps, vintage area rugs, geometric wall art, and vintage-inspired lighting fixtures.",
    'scandinavian': "Stage this living room in Scandinavian style with light wood furniture, neutral textiles, cozy textures, and minimalist décor. Add a simple sofa with knit throw pillows, a wooden coffee table, accent chairs, side tables with simple lamps, natural fiber rugs, minimalist wall art, and plenty of plants. Emphasize functionality and hygge comfort.",
    'luxury': "Stage this living room with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add a plush sectional with velvet throw pillows, a marble coffee table with crystal accessories, tufted accent chairs, ornate side tables with crystal lamps, luxury area rugs, elegant wall art, and chandelier lighting. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this living room with coastal-inspired furniture in light blues, whites, and natural textures. Add a white or light blue sofa with nautical throw pillows, a weathered coffee table, wicker accent chairs, side tables with rope-wrapped lamps, jute area rugs, ocean-themed wall art, and natural lighting. Create a relaxed, airy feel.",
    'farmhouse': "Stage this living room with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a comfortable sofa with floral throw pillows, a wooden coffee table, vintage accent chairs, distressed side tables with mason jar lamps, braided rugs, country wall art, and warm lighting. Create a charming, country-inspired atmosphere.",
    'custom': "Stage this living room with the furniture and decor the user asks for."
  },
  'Dining room': {
    'standard': "Stage this dining room with stylish, contemporary furniture that appeals to a broad audience. Add a dining table with a tablecloth, dining chairs with seat cushions, a sideboard or buffet, table centerpiece, placemats, dinnerware, glassware, napkins, table runner, wall art, and pendant lighting. Use neutral colors and clean lines.",
    'modern': "Stage this dining room in a modern style with a sleek dining table with a minimalist tablecloth, contemporary chairs with clean lines, a modern sideboard, geometric centerpiece, modern placemats, contemporary dinnerware, sleek glassware, modern napkins, geometric table runner, abstract wall art, and statement pendant lighting. Use neutral colors and geometric accents.",
    'midcentury': "Stage this dining room with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage dining table with a retro tablecloth, Eames-style chairs, a teak sideboard, atomic centerpiece, vintage placemats, mid-century dinnerware, retro glassware, patterned napkins, geometric table runner, vintage wall art, and atomic lighting fixtures.",
    'scandinavian': "Stage this dining room in Scandinavian style with light wood furniture, neutral textiles, and minimalist décor. Add a simple wooden table with a linen tablecloth, wooden chairs with seat cushions, a minimalist sideboard, natural centerpiece, simple placemats, white dinnerware, clear glassware, linen napkins, simple table runner, minimalist wall art, and pendant lighting. Emphasize functionality and natural materials.",
    'luxury': "Stage this dining room with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add a marble dining table with a silk tablecloth, upholstered dining chairs with velvet cushions, an ornate sideboard, crystal centerpiece, luxury placemats, fine china, crystal glassware, silk napkins, brocade table runner, elegant wall art, and chandelier lighting. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this dining room with coastal-inspired furniture in light blues, whites, and natural textures. Add a weathered dining table with a nautical tablecloth, wicker chairs with striped cushions, a distressed sideboard, seashell centerpiece, coastal placemats, white dinnerware, blue glassware, striped napkins, rope table runner, ocean wall art, and coastal lighting. Add nautical elements and beach-inspired décor.",
    'farmhouse': "Stage this dining room with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a wooden dining table with a checkered tablecloth, vintage chairs with floral cushions, a distressed sideboard, mason jar centerpiece, burlap placemats, vintage dinnerware, mason jar glassware, gingham napkins, burlap table runner, country wall art, and rustic lighting.",
    'custom': "Stage this dining room with the furniture and decor the user asks for."
  },
  'Kitchen': {
    'standard': "Stage this kitchen with stylish, contemporary elements that appeal to a broad audience. Add modern appliances including a refrigerator, oven, microwave, dishwasher, and coffee maker. Include a kitchen island or dining table, bar stools, pendant lighting, backsplash, countertop accessories, fruit bowl, cutting boards, kitchen towels, potted herbs, and wall art. Focus on clean lines, neutral colors, and functional storage solutions.",
    'modern': "Stage this kitchen in a modern style with sleek stainless steel appliances including a refrigerator, oven, microwave, dishwasher, and coffee maker. Add a minimalist kitchen island, modern bar stools, geometric pendant lighting, subway tile backsplash, contemporary countertop accessories, modern fruit bowl, sleek cutting boards, minimalist kitchen towels, modern potted plants, and abstract wall art. Use neutral colors and geometric accents.",
    'midcentury': "Stage this kitchen with mid-century modern elements featuring warm wood tones, vintage-inspired lighting, and geometric patterns. Add retro appliances including a vintage-style refrigerator, oven, microwave, and coffee maker. Include a teak kitchen island, atomic bar stools, vintage pendant lighting, geometric backsplash, retro countertop accessories, atomic fruit bowl, wooden cutting boards, patterned kitchen towels, vintage potted plants, and atomic wall art.",
    'scandinavian': "Stage this kitchen in Scandinavian style with light wood elements, neutral colors, and minimalist décor. Add clean white appliances including a refrigerator, oven, microwave, and coffee maker. Include a wooden kitchen island, simple bar stools, pendant lighting, white tile backsplash, minimalist countertop accessories, wooden fruit bowl, natural cutting boards, linen kitchen towels, herb plants, and minimalist wall art. Emphasize functionality and natural materials.",
    'luxury': "Stage this kitchen with high-end luxury elements featuring rich materials like marble, premium finishes, and elegant accessories. Add premium appliances including a professional refrigerator, double oven, wine cooler, and espresso machine. Include a marble kitchen island, upholstered bar stools, chandelier lighting, marble backsplash, crystal countertop accessories, luxury fruit bowl, marble cutting boards, silk kitchen towels, elegant plants, and luxury wall art. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this kitchen with coastal-inspired elements in light blues, whites, and natural textures. Add white or stainless steel appliances including a refrigerator, oven, microwave, and coffee maker. Include a weathered kitchen island, wicker bar stools, coastal pendant lighting, blue tile backsplash, nautical countertop accessories, seashell fruit bowl, wooden cutting boards, striped kitchen towels, coastal plants, and ocean wall art. Add nautical touches and beach-inspired décor.",
    'farmhouse': "Stage this kitchen with rustic farmhouse elements featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add vintage-style appliances including a retro refrigerator, oven, and coffee maker. Include a wooden kitchen island, vintage bar stools, rustic pendant lighting, brick backsplash, vintage countertop accessories, mason jar fruit bowl, wooden cutting boards, gingham kitchen towels, herb garden, and country wall art. Create a charming, rustic atmosphere.",
    'custom': "Stage this kitchen with the elements and decor the user asks for."
  },
  'Office': {
    'standard': "Stage this office with stylish, contemporary furniture that appeals to a broad audience. Add a desk with desk lamp, ergonomic office chair, filing cabinet, bookshelf, desk organizer, computer monitor, keyboard, mouse pad, desk plants, wall art, and task lighting. Use neutral colors and clean lines.",
    'modern': "Stage this office in a modern style with a sleek desk with modern desk lamp, contemporary ergonomic chair, minimalist filing cabinet, modern bookshelf, geometric desk organizer, sleek computer monitor, wireless keyboard, modern mouse pad, modern desk plants, abstract wall art, and statement task lighting. Use neutral colors and geometric accents.",
    'midcentury': "Stage this office with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage desk with atomic desk lamp, Eames-style office chair, teak filing cabinet, vintage bookshelf, retro desk organizer, vintage computer monitor, retro keyboard, atomic mouse pad, vintage desk plants, geometric wall art, and atomic lighting fixtures.",
    'scandinavian': "Stage this office in Scandinavian style with light wood furniture, neutral textiles, and minimalist décor. Add a simple wooden desk with pendant lamp, wooden office chair, minimalist filing cabinet, wooden bookshelf, simple desk organizer, white computer monitor, wooden keyboard, natural mouse pad, herb plants, minimalist wall art, and natural lighting. Emphasize functionality and natural materials.",
    'luxury': "Stage this office with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add a marble desk with crystal desk lamp, tufted office chair, luxury filing cabinet, ornate bookshelf, crystal desk organizer, premium computer monitor, luxury keyboard, marble mouse pad, elegant plants, luxury wall art, and chandelier lighting. Create an opulent, sophisticated workspace.",
    'coastal': "Stage this office with coastal-inspired furniture in light blues, whites, and natural textures. Add a weathered desk with coastal desk lamp, wicker office chair, distressed filing cabinet, coastal bookshelf, nautical desk organizer, white computer monitor, rope-wrapped keyboard, coastal mouse pad, coastal plants, ocean wall art, and natural lighting. Add nautical elements and beach-inspired décor.",
    'farmhouse': "Stage this office with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a wooden desk with mason jar desk lamp, vintage office chair, distressed filing cabinet, wooden bookshelf, vintage desk organizer, vintage computer monitor, wooden keyboard, burlap mouse pad, herb garden, country wall art, and rustic lighting.",
    'custom': "Stage this office with the furniture and decor the user asks for."
  },
  'Bathroom': {
    'standard': "Stage this bathroom with clean, contemporary elements. Add bathroom essentials including a toilet, sink with faucet, shower or bathtub, vanity with mirror, towel rack, bath mat, shower curtain, soap dispenser, toothbrush holder, hand towels, bath towels, toilet paper holder, wastebasket, and wall art. Keep it minimal and functional with neutral colors.",
    'modern': "Stage this bathroom in a modern style with sleek fixtures, minimalist accessories, and contemporary lighting. Add a modern toilet, sleek sink with modern faucet, walk-in shower, floating vanity with backlit mirror, modern towel rack, geometric bath mat, frameless shower door, modern soap dispenser, minimalist toothbrush holder, modern hand towels, sleek bath towels, modern toilet paper holder, contemporary wastebasket, and abstract wall art. Use neutral colors and clean lines.",
    'midcentury': "Stage this bathroom with mid-century modern elements featuring warm wood tones and vintage-inspired lighting. Add a vintage toilet, retro sink with atomic faucet, vintage bathtub, teak vanity with vintage mirror, atomic towel rack, geometric bath mat, vintage shower curtain, retro soap dispenser, atomic toothbrush holder, patterned hand towels, vintage bath towels, atomic toilet paper holder, vintage wastebasket, and geometric wall art. Add geometric patterns in textiles.",
    'scandinavian': "Stage this bathroom in Scandinavian style with light wood elements, neutral colors, and minimalist décor. Add a clean white toilet, simple sink with wooden faucet, freestanding bathtub, wooden vanity with round mirror, wooden towel rack, natural bath mat, simple shower curtain, wooden soap dispenser, minimalist toothbrush holder, linen hand towels, natural bath towels, wooden toilet paper holder, natural wastebasket, and minimalist wall art. Emphasize functionality and natural materials.",
    'luxury': "Stage this bathroom with high-end luxury elements featuring rich materials like marble, premium finishes, and elegant accessories. Add a luxury toilet, marble sink with gold faucet, freestanding bathtub, marble vanity with ornate mirror, crystal towel rack, luxury bath mat, frameless glass shower, crystal soap dispenser, luxury toothbrush holder, silk hand towels, plush bath towels, gold toilet paper holder, marble wastebasket, and elegant wall art. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this bathroom with coastal-inspired elements in light blues, whites, and natural textures. Add a white toilet, coastal sink with nautical faucet, walk-in shower, weathered vanity with coastal mirror, rope towel rack, coastal bath mat, nautical shower curtain, seashell soap dispenser, coastal toothbrush holder, striped hand towels, white bath towels, coastal toilet paper holder, wicker wastebasket, and ocean wall art. Add nautical touches and beach-inspired décor.",
    'farmhouse': "Stage this bathroom with rustic farmhouse elements featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a vintage toilet, farmhouse sink with vintage faucet, clawfoot bathtub, wooden vanity with vintage mirror, rustic towel rack, braided bath mat, vintage shower curtain, mason jar soap dispenser, vintage toothbrush holder, gingham hand towels, vintage bath towels, rustic toilet paper holder, wooden wastebasket, and country wall art. Create a charming, rustic atmosphere.",
    'custom': "Stage this bathroom with the elements and decor the user asks for."
  }
};
