// Prompt matrix for room type and furniture style combinations
//
// THIS FILE IS THE *STYLE* LAYER, AND ONLY THAT: what MOVABLE furniture and decor to add.
// It must never ask the model to add, install or replace a PERMANENT element — see
// PERMANENT_ELEMENT_DEFINITION in ./preservation-rules.js for the line, and use that
// definition rather than re-deciding it here.
//
// WHY THAT RULE EXISTS. These prompts used to read "Add a walk-in shower", "Add a subway
// tile backsplash", "Add chandelier lighting", "and natural lighting" — and the model does
// what it is told, so it tiled walls, hung fixtures from ceilings, and enlarged or invented
// windows to deliver the "natural lighting" it had been asked for. Meanwhile the block a
// thousand characters later forbade touching exactly those things. Faced with an itemised
// shopping list on one side and an abstract rule on the other, a model follows the list.
// The contradiction was the bug; removing one half of it is the fix.
//
// The rooms still read as themselves because the tub, the counters and the backsplash are
// ALREADY IN THE PHOTOGRAPH. Staging dresses a room; it does not renovate one. Where a
// style needs to look different, it does so through textiles, movable furniture, lamps that
// plug in, art and accessories — which is what this file is for.
//
// The earlier round of this same cleanup: every bathroom prompt used to open with "Add a
// <style> toilet", and one duly appeared on the hardwood floor of a photo that was never a
// bathroom. The free-hanging shower curtains came from the same instinct — asked for a
// curtain with no enclosure to hang it on, the model hung it from the ceiling.
//
// test/staging/prompt-matrix-permanence.test.js scans these strings and fails the build on a
// banned noun, because the previous version of this rule was a comment, and a comment does
// not block a deploy.
/**
 * Nested lookup of room-type + furniture-style -> staging prompt text; consumed by
 * generatePrompt(). Every room type carries the same 8 style keys, and callers index
 * it as `promptMatrix[roomType]?.[furnitureStyle]` with a fallback to the 'standard' entry.
 * @type {Record<'Bedroom'|'Living room'|'Dining room'|'Kitchen'|'Office'|'Bathroom'|'Outdoors'|'Dorm', Record<'standard'|'modern'|'midcentury'|'scandinavian'|'luxury'|'coastal'|'farmhouse'|'custom', string>>}
 */
export const promptMatrix = {
  'Bedroom': {
    'standard': "Stage this bedroom with stylish, contemporary furniture that appeals to a broad audience. Add a modern bed with clean lines, matching nightstands with table lamps, a dresser with mirror, soft neutral bedding with throw pillows, a cozy armchair or bench, and wall art. Use neutral colors and clean lines throughout.",
    'modern': "Stage this bedroom in a modern style with a low-profile platform bed in neutral tones, sleek nightstands with minimalist table lamps, a contemporary dresser with modern hardware, luxury bedding with geometric throw pillows, a sculptural accent chair, modern wall art, and a sculptural floor lamp. Add a large area rug and keep accessories minimal with clean, geometric designs.",
    'midcentury': "Stage this bedroom with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage-inspired bed frame, matching nightstands with retro lamps, a teak dresser, mid-century bedding with bold patterns, an Eames-style chair, vintage wall art, and a tripod or globe floor lamp.",
    'scandinavian': "Stage this bedroom in Scandinavian style with light wood furniture, neutral textiles, cozy textures, and minimalist décor. Add a simple bed frame, wooden nightstands, a minimalist dresser, soft white bedding with knit throws, a cozy reading chair, natural wood accessories, and simple wall art. Focus on functionality, hygge comfort, and natural materials.",
    'luxury': "Stage this bedroom with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add an upholstered headboard, marble-topped nightstands with crystal lamps, a luxury dresser with gold hardware, silk bedding with velvet throw pillows, a tufted accent chair, ornate mirrors, and elegant wall art. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this bedroom with coastal-inspired furniture in light blues, whites, and natural textures. Add a white or light wood bed frame, wicker nightstands, a distressed dresser, nautical bedding with striped throw pillows, a rattan chair, seashell accessories, and ocean-themed wall art. Create an airy, relaxed styling with a light, breezy palette.",
    'farmhouse': "Stage this bedroom with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a wooden bed frame, vintage nightstands with mason jar lamps, a distressed dresser, floral bedding with quilted throws, a rocking chair, vintage accessories, and country-style wall art. Create a charming, country-inspired atmosphere.",
    'custom': "Stage this bedroom with the furniture and decor the user asks for."
  },
  'Living room': {
    'standard': "Stage this living room with stylish, contemporary furniture that appeals to a broad audience. Add a comfortable sofa with throw pillows, a coffee table with decorative items, an entertainment center or TV stand, accent chairs, side tables with table lamps, an area rug, wall art, and plants. Use neutral colors and clean lines.",
    'modern': "Stage this living room in a modern style by adding a low-profile sectional sofa in neutral colors with geometric throw pillows, a sleek glass or polished stone coffee table with minimalist decor, an accent chair with bold sculptural design, modern side tables with contemporary lamps, a large area rug, abstract wall art, and a sculptural arc floor lamp.",
    'midcentury': "Stage this living room with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage sofa with colorful throw pillows, a teak coffee table, Eames-style chairs, retro side tables with atomic lamps, vintage area rugs, geometric wall art, and a tripod floor lamp.",
    'scandinavian': "Stage this living room in Scandinavian style with light wood furniture, neutral textiles, cozy textures, and minimalist décor. Add a simple sofa with knit throw pillows, a wooden coffee table, accent chairs, side tables with simple lamps, natural fiber rugs, minimalist wall art, and plenty of plants. Emphasize functionality and hygge comfort.",
    'luxury': "Stage this living room with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add a plush sectional with velvet throw pillows, a marble coffee table with crystal accessories, tufted accent chairs, ornate side tables with crystal lamps, luxury area rugs, elegant wall art, and a statement floor lamp. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this living room with coastal-inspired furniture in light blues, whites, and natural textures. Add a white or light blue sofa with nautical throw pillows, a weathered coffee table, wicker accent chairs, side tables with rope-wrapped lamps, jute area rugs, and ocean-themed wall art. Create a relaxed, airy feel with a bright, breezy palette.",
    'farmhouse': "Stage this living room with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a comfortable sofa with floral throw pillows, a wooden coffee table, vintage accent chairs, distressed side tables with mason jar lamps, braided rugs, and country wall art. Create a charming, country-inspired atmosphere.",
    'custom': "Stage this living room with the furniture and decor the user asks for."
  },
  'Dining room': {
    'standard': "Stage this dining room with stylish, contemporary furniture that appeals to a broad audience. Add a dining table with a tablecloth, dining chairs with seat cushions, a sideboard or buffet, table centerpiece, placemats, dinnerware, glassware, napkins, table runner, and wall art. Use neutral colors and clean lines.",
    'modern': "Stage this dining room in a modern style with a sleek dining table with a minimalist tablecloth, contemporary chairs with clean lines, a modern sideboard, geometric centerpiece, modern placemats, contemporary dinnerware, sleek glassware, modern napkins, geometric table runner, and abstract wall art. Use neutral colors and geometric accents.",
    'midcentury': "Stage this dining room with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage dining table with a retro tablecloth, Eames-style chairs, a teak sideboard, atomic centerpiece, vintage placemats, mid-century dinnerware, retro glassware, patterned napkins, geometric table runner, and vintage wall art.",
    'scandinavian': "Stage this dining room in Scandinavian style with light wood furniture, neutral textiles, and minimalist décor. Add a simple wooden table with a linen tablecloth, wooden chairs with seat cushions, a minimalist sideboard, natural centerpiece, simple placemats, white dinnerware, clear glassware, linen napkins, simple table runner, and minimalist wall art. Emphasize functionality and natural materials.",
    'luxury': "Stage this dining room with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add a marble dining table with a silk tablecloth, upholstered dining chairs with velvet cushions, an ornate sideboard, crystal centerpiece, luxury placemats, fine china, crystal glassware, silk napkins, brocade table runner, and elegant wall art. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this dining room with coastal-inspired furniture in light blues, whites, and natural textures. Add a weathered dining table with a nautical tablecloth, wicker chairs with striped cushions, a distressed sideboard, seashell centerpiece, coastal placemats, white dinnerware, blue glassware, striped napkins, rope table runner, and ocean wall art. Add nautical elements and beach-inspired décor.",
    'farmhouse': "Stage this dining room with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a wooden dining table with a checkered tablecloth, vintage chairs with floral cushions, a distressed sideboard, mason jar centerpiece, burlap placemats, vintage dinnerware, mason jar glassware, gingham napkins, burlap table runner, and country wall art.",
    'custom': "Stage this dining room with the furniture and decor the user asks for."
  },
  /* KITCHENS ARE ALREADY BUILT. The counters, cabinetry, backsplash, sink and built-in
     appliances in the photo are the kitchen — every one of them is plumbed, wired or fixed
     to the structure. These prompts used to order a fresh set ("Add a minimalist kitchen
     island, subway tile backsplash, geometric pendant lighting, stainless steel appliances
     including a dishwasher"), which is a renovation, not a staging. What is left below is
     what a stager actually carries in: stools, textiles, boards, bowls, plants and art. */
  'Kitchen': {
    'standard': "Stage this kitchen with stylish, contemporary styling that appeals to a broad audience. Keep the existing cabinetry, counters, backsplash, sink and built-in appliances exactly as photographed — style around them. Add bar stools at any existing island or counter, tasteful countertop accessories, a fruit bowl, cutting boards, a kettle or coffee maker on the counter, folded kitchen towels, potted herbs, and wall art. Focus on clean lines, neutral colors, and uncluttered counters.",
    'modern': "Stage this kitchen in a modern style, keeping the existing cabinetry, counters, backsplash, sink and built-in appliances exactly as photographed. Add sleek modern bar stools at any existing island or counter, contemporary countertop accessories in matte black or brushed metal, a modern fruit bowl, sleek cutting boards, a minimalist coffee maker, crisply folded kitchen towels, modern potted plants, and abstract wall art. Use neutral colors, geometric accents and near-empty counters.",
    'midcentury': "Stage this kitchen with mid-century modern styling, keeping the existing cabinetry, counters, backsplash, sink and built-in appliances exactly as photographed. Add atomic bar stools at any existing island or counter, retro countertop accessories in warm enamel tones, an atomic fruit bowl, teak cutting boards, a retro-styled kettle, patterned kitchen towels, potted plants in tapered-leg pots, and atomic wall art. Let warm wood tones and geometric patterns carry the style.",
    'scandinavian': "Stage this kitchen in Scandinavian style, keeping the existing cabinetry, counters, backsplash, sink and built-in appliances exactly as photographed. Add simple light-wood bar stools at any existing island or counter, minimalist countertop accessories, a wooden fruit bowl, natural cutting boards, a plain white kettle, linen kitchen towels, potted herbs, and minimalist wall art. Emphasize functionality, natural materials and clear surfaces.",
    'luxury': "Stage this kitchen with high-end styling, keeping the existing cabinetry, counters, backsplash, sink and built-in appliances exactly as photographed. Add upholstered bar stools at any existing island or counter, crystal and polished-metal countertop accessories, a luxury fruit bowl, marble cutting boards, an espresso maker on the counter, fine linen kitchen towels, elegant orchids or plants, and luxury wall art. Create an opulent, sophisticated atmosphere through materials and styling alone.",
    'coastal': "Stage this kitchen with coastal-inspired styling, keeping the existing cabinetry, counters, backsplash, sink and built-in appliances exactly as photographed. Add wicker bar stools at any existing island or counter, nautical countertop accessories, a seashell fruit bowl, wooden cutting boards, striped kitchen towels, coastal plants, and ocean wall art. Keep the palette bright, breezy and relaxed in light blues, whites and natural textures.",
    'farmhouse': "Stage this kitchen with rustic farmhouse styling, keeping the existing cabinetry, counters, backsplash, sink and built-in appliances exactly as photographed. Add vintage wooden bar stools at any existing island or counter, vintage countertop accessories, a mason jar fruit bowl, wooden cutting boards and a bread board, gingham kitchen towels, a potted herb garden on the windowsill, and country wall art. Use reclaimed wood, vintage pieces and warm, earthy tones.",
    'custom': "Stage this kitchen with the elements and decor the user asks for."
  },
  'Office': {
    'standard': "Stage this office with stylish, contemporary furniture that appeals to a broad audience. Add a desk with a desk lamp, ergonomic office chair, filing cabinet, bookshelf, desk organizer, computer monitor, keyboard, mouse pad, desk plants, and wall art. Use neutral colors and clean lines.",
    'modern': "Stage this office in a modern style with a sleek desk with a modern desk lamp, contemporary ergonomic chair, minimalist filing cabinet, modern bookshelf, geometric desk organizer, sleek computer monitor, wireless keyboard, modern mouse pad, modern desk plants, and abstract wall art. Use neutral colors and geometric accents.",
    'midcentury': "Stage this office with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a vintage desk with an atomic desk lamp, Eames-style office chair, teak filing cabinet, vintage bookshelf, retro desk organizer, vintage computer monitor, retro keyboard, atomic mouse pad, vintage desk plants, and geometric wall art.",
    'scandinavian': "Stage this office in Scandinavian style with light wood furniture, neutral textiles, and minimalist décor. Add a simple wooden desk with a light-wood desk lamp, wooden office chair, minimalist filing cabinet, wooden bookshelf, simple desk organizer, white computer monitor, wooden keyboard, natural mouse pad, herb plants, and minimalist wall art. Emphasize functionality and natural materials.",
    'luxury': "Stage this office with high-end luxury furniture featuring rich materials like marble, velvet, and gold accents. Add a marble desk with a crystal desk lamp, tufted office chair, luxury filing cabinet, ornate bookshelf, crystal desk organizer, premium computer monitor, luxury keyboard, marble mouse pad, elegant plants, and luxury wall art. Create an opulent, sophisticated workspace.",
    'coastal': "Stage this office with coastal-inspired furniture in light blues, whites, and natural textures. Add a weathered desk with a coastal desk lamp, wicker office chair, distressed filing cabinet, coastal bookshelf, nautical desk organizer, white computer monitor, rope-wrapped keyboard, coastal mouse pad, coastal plants, and ocean wall art. Add nautical elements and beach-inspired décor.",
    'farmhouse': "Stage this office with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a wooden desk with a mason jar desk lamp, vintage office chair, distressed filing cabinet, wooden bookshelf, vintage desk organizer, vintage computer monitor, wooden keyboard, burlap mouse pad, herb garden, and country wall art.",
    'custom': "Stage this office with the furniture and decor the user asks for."
  },
  /* THE ONE ROOM TYPE ALLOWED TO INSTALL A PERMANENT ELEMENT, and the only one — read this
     before copying any wording below into another room.

     THE HISTORY, because it is what the current shape is built around. Every one of these
     prompts used to open "Add a <style> toilet", unconditionally, and because the model does
     what it is told it installed one — including on the hardwood floor of a photo that was
     never a bathroom. Asked for a shower curtain with no enclosure to hang it on, it hung one
     from the ceiling. Asked for a "walk-in shower" or a "floating vanity", it built one, over
     a window in the worst cases. On 2026-08-17 the fixtures were struck out entirely and the
     prompts reduced to accessories.

     That fixed the damage and left a different hole: a room with no plumbing in it cannot be
     staged as a bathroom at all, because "stage this as a bathroom" collapses into "decorate
     this room". Since 2026-08-18 these prompts may install fixtures again — but conditionally,
     which is the difference that matters, and each of the three failures above is now blocked
     by something specific rather than by a blanket ban:
       - a toilet in the wrong kind of room  -> the permission is scoped to roomType
         'Bathroom' alone (interiorPreservationRulesFor in ./preservation-rules.js);
       - a fixture built over a window       -> the window/door COUNT rule is untouched and
         shared by both variants, and every entry below repeats the site rule verbatim;
       - a curtain hung from the ceiling     -> ROOM_TYPE_CONSTRAINTS['Bathroom'] requires
         something to hang it on.

     THREE PHRASES BELOW ARE LOAD-BEARING and are asserted verbatim in all seven styles by
     test/staging/prompt-matrix-permanence.test.js: "exactly as photographed", "never add a
     second one", and "never across a window, door or glazed wall". Keep-what-exists is
     written FIRST in every entry on purpose — it is the sentence protecting a real customer's
     bathroom, and the install case reads as an exception to it rather than the reverse.

     'custom' stays a passthrough. Its rule half lives in ROOM_TYPE_CONSTRAINTS['Bathroom'],
     which is emitted for every style, because free text replaces this entry wholesale. */
  'Bathroom': {
    'standard': "Stage this bathroom with clean, contemporary styling. Keep any bath, shower, basin, taps, WC, vanity, mirror and tiling already in the photograph exactly as photographed — style around them, and never add a second one. Where the room has none, fit a clean contemporary bath or a walk-in shower behind a plain glass screen, a wall-hung basin with chrome taps, a simple vanity and a concealed-cistern WC, standing on the existing floor against solid wall, never across a window, door or glazed wall. Add a bath mat, a soap dispenser, a toothbrush holder, neatly folded hand towels and bath towels, a small plant, a candle or tray of toiletries, a wastebasket, and wall art. Keep it minimal and functional with neutral colors.",
    'modern': "Stage this bathroom in a modern style. Keep any bath, shower, basin, taps, WC, vanity, mirror and tiling already in the photograph exactly as photographed — style around them, and never add a second one. Where the room has none, fit a frameless walk-in shower, a floating vanity with an integrated basin, matte-black or chrome taps and a wall-hung WC, standing on the existing floor against solid wall, never across a window, door or glazed wall. Add a geometric bath mat, a matte-black or chrome soap dispenser, a minimalist toothbrush holder, crisply folded modern hand towels and bath towels, a sculptural plant, a slim tray of toiletries, a contemporary wastebasket, and abstract wall art. Use neutral colors and clean lines.",
    'midcentury': "Stage this bathroom with mid-century modern styling. Keep any bath, shower, basin, taps, WC, vanity, mirror and tiling already in the photograph exactly as photographed — style around them, and never add a second one. Where the room has none, fit a walk-in shower behind a slim-framed screen, a teak vanity on tapered legs with an integrated basin, brushed-brass taps and a compact WC, standing on the existing floor against solid wall, never across a window, door or glazed wall. Add a geometric bath mat, a retro soap dispenser, an atomic toothbrush holder, patterned hand towels and vintage bath towels, a trailing plant in a tapered-leg pot, a teak tray of toiletries, a vintage wastebasket, and geometric wall art. Let warm wood tones and geometric patterns in the textiles carry the style.",
    'scandinavian': "Stage this bathroom in Scandinavian style. Keep any bath, shower, basin, taps, WC, vanity, mirror and tiling already in the photograph exactly as photographed — style around them, and never add a second one. Where the room has none, fit a walk-in shower behind a plain glass screen, a pale-wood vanity with an integrated basin, simple matte taps and a compact WC, standing on the existing floor against solid wall, never across a window, door or glazed wall. Add a natural bath mat, a wooden soap dispenser, a minimalist toothbrush holder, linen hand towels and natural bath towels, a eucalyptus stem or small plant, a pale-wood tray of toiletries, a natural woven wastebasket, and minimalist wall art. Emphasize functionality, light and natural materials.",
    'luxury': "Stage this bathroom with high-end styling. Keep any bath, shower, basin, taps, WC, vanity, mirror and tiling already in the photograph exactly as photographed — style around them, and never add a second one. Where the room has none, fit a freestanding stone bath, a marble-topped vanity with twin basins and polished-brass taps, a walk-in shower behind a clear glass screen and a concealed-cistern WC, standing on the existing floor against solid wall, never across a window, door or glazed wall. Add a luxury bath mat, a crystal soap dispenser, an elegant toothbrush holder, silk hand towels and plush rolled bath towels, an orchid, a marble tray of fine toiletries and a candle, a polished wastebasket, and elegant wall art. Create an opulent, spa-like atmosphere through textiles and accessories.",
    'coastal': "Stage this bathroom with coastal-inspired styling. Keep any bath, shower, basin, taps, WC, vanity, mirror and tiling already in the photograph exactly as photographed — style around them, and never add a second one. Where the room has none, fit a bath or a walk-in shower behind a clear glass screen, a white shaker vanity with an integrated basin, brushed-nickel taps and a simple WC, standing on the existing floor against solid wall, never across a window, door or glazed wall. Add a coastal bath mat, a seashell soap dispenser, a coastal toothbrush holder, striped hand towels and white bath towels, an airy plant, a woven tray of toiletries, a wicker wastebasket, and ocean wall art. Keep the palette light blues, whites and natural textures.",
    'farmhouse': "Stage this bathroom with rustic farmhouse styling. Keep any bath, shower, basin, taps, WC, vanity, mirror and tiling already in the photograph exactly as photographed — style around them, and never add a second one. Where the room has none, fit a roll-top clawfoot bath, a pedestal washstand with exposed brassware, a walk-in shower behind a simply framed screen and a traditional WC, standing on the existing floor against solid wall, never across a window, door or glazed wall. Add a braided bath mat, a mason jar soap dispenser, a vintage toothbrush holder, gingham hand towels and vintage bath towels, a small potted plant, a wooden crate or tray of toiletries, a wooden wastebasket, and country wall art. Use reclaimed wood, vintage pieces and warm, earthy tones.",
    'custom': "Stage this bathroom with the elements and decor the user asks for."
  },
  'Outdoors': {
    'standard': "Stage this outdoor space with stylish, contemporary furniture that appeals to a broad audience. Add comfortable outdoor seating like a sectional or sofas with weather-resistant cushions, a dining table with chairs, an outdoor rug, a freestanding patio umbrella, plug-in string lights, planters with greenery, decorative accent pieces, and a portable fire pit or patio heater. Use neutral colors and durable materials.",
    'modern': "Stage this outdoor space in a modern style with sleek, minimalist outdoor furniture featuring clean lines and contemporary designs. Add a modern sectional with geometric cushions, a sleek dining set, modern outdoor rugs, a minimalist freestanding patio umbrella, plug-in string lights, modern planters with tropical plants, geometric accent pieces, and a portable modern fire bowl. Use neutral colors and geometric accents.",
    'midcentury': "Stage this outdoor space with mid-century modern furniture featuring warm wood tones, tapered legs, and iconic silhouettes. Add a retro outdoor sectional with colorful cushions, a teak dining set, vintage outdoor rugs, an atomic freestanding patio umbrella, vintage string lights, retro planters, atomic accent pieces, and a portable vintage fire bowl. Add geometric patterns and warm colors.",
    'scandinavian': "Stage this outdoor space in Scandinavian style with light wood furniture, neutral textiles, and minimalist décor. Add simple outdoor seating with natural cushions, a wooden dining set, natural fiber rugs, a simple freestanding patio umbrella, minimalist string lights, wooden planters with herbs, minimalist accent pieces, and a portable fire bowl. Emphasize functionality and natural materials.",
    'luxury': "Stage this outdoor space with high-end luxury furniture featuring premium materials and elegant accessories. Add a luxury outdoor sectional with plush cushions, a marble dining set, luxury outdoor rugs, an elegant freestanding patio umbrella, crystal string lights, ornate planters with elegant plants, luxury accent pieces, and a portable fire bowl. Create an opulent, sophisticated atmosphere.",
    'coastal': "Stage this outdoor space with coastal-inspired furniture in light blues, whites, and natural textures. Add a wicker outdoor sectional with nautical cushions, a weathered dining set, coastal outdoor rugs, a nautical freestanding patio umbrella, coastal string lights, seashell planters, ocean-themed accent pieces, and a portable coastal fire bowl. Add nautical touches and beach-inspired décor.",
    'farmhouse': "Stage this outdoor space with rustic farmhouse furniture featuring reclaimed wood, vintage pieces, and cozy textiles in warm, earthy tones. Add a wooden outdoor sectional with floral cushions, a rustic dining set, braided outdoor rugs, a vintage freestanding patio umbrella, rustic string lights, mason jar planters, country accent pieces, and a portable rustic fire bowl. Create a charming, country-inspired atmosphere.",
    'custom': "Stage this outdoor space with the furniture and decor the user asks for."
  },
  // College dorm. The university-issued desk, bed frame/posts, wardrobe and dresser are
  // FIXED — that rule lives in ROOM_TYPE_CONSTRAINTS (room-constraints.js) rather than in
  // these strings, because it must also apply to the 'custom' style (which bypasses this
  // matrix entirely) and must survive a remove-furniture request. Every light named below
  // plugs in or clips on, which is also what that block requires.
  'Dorm': {
    'standard': "Stage this college dorm room around the university-issued furniture already in it. Add a made bed on the existing frame with a mattress topper, comforter, sheets and pillows, a small area rug that fits the open floor, a desk lamp and organized desk-top supplies on the existing desk, a desk chair, under-bed storage bins, a slim laundry hamper, a full-length or over-door mirror, a power strip, string lights or a clip lamp, wall art and photos, and a plant or two. Keep colors neutral and coordinated, and keep every walkway clear.",
    'modern': "Stage this college dorm room in a modern style around the university-issued furniture already in it. Add crisp solid-color bedding in a restrained palette with geometric throw pillows, a low-pile rug with a simple graphic pattern, a matte-black or brushed-metal desk lamp, a minimalist desk organizer and monitor riser, a sleek task chair, flat-front under-bed storage bins, a collapsible hamper, an LED strip or linear clip light, framed abstract prints, and a single sculptural plant. Keep surfaces clear and the palette tight.",
    'midcentury': "Stage this college dorm room with mid-century modern accents layered around the university-issued furniture already in it. Add bedding in warm mustard, olive or burnt-orange tones with geometric throw pillows, a low-pile rug with an atomic pattern, a dome or globe desk lamp in a warm metal finish, a walnut-toned desk organizer and small record or book caddy, a molded-shell desk chair, woven storage baskets under the bed, a canvas hamper, framed geometric prints, and a trailing plant in a tapered-leg pot. Let the warm retro palette do the work — the issued furniture stays untouched.",
    'scandinavian': "Stage this college dorm room in Scandinavian style around the university-issued furniture already in it. Add soft white or oatmeal bedding with a chunky knit throw and linen pillows, a flat-weave neutral rug, a simple light-wood or white desk lamp, a pared-back desk organizer in pale wood, a light-wood desk chair with a sheepskin draped over it, woven seagrass under-bed baskets, a linen hamper, a slim full-length mirror, one or two minimalist line-art prints, and a few small potted plants. Emphasize light, warmth, hygge and uncluttered surfaces.",
    'luxury': "Stage this college dorm room as an elevated, high-end version of itself, working around the university-issued furniture already in it. Add hotel-quality white bedding with a plush duvet, layered throw pillows and a velvet lumbar cushion, a soft high-pile rug, a polished brass or crystal desk lamp, a leather desk blotter and refined desk accessories, an upholstered desk chair, monogrammed storage boxes under the bed, a lined hamper, a gold-framed mirror, elegant framed art, and a well-styled plant in a ceramic pot. Achieve the upgrade entirely through textiles, lighting and accessories — never by replacing the issued furniture.",
    'coastal': "Stage this college dorm room with coastal styling around the university-issued furniture already in it. Add white and soft-blue bedding with striped throw pillows and a lightweight woven blanket, a jute or flat-weave striped rug, a rope-wrapped or driftwood-toned desk lamp, a woven desk organizer, a light desk chair with a canvas cushion, wicker under-bed baskets, a canvas hamper, a round rope-framed mirror, framed ocean and shoreline prints, and an airy plant. Keep the palette bright, breezy and relaxed.",
    'farmhouse': "Stage this college dorm room with cozy farmhouse styling around the university-issued furniture already in it. Add a quilted or patchwork comforter with gingham and floral throw pillows, a braided or flat-weave rug in warm earthy tones, a mason-jar or matte-black desk lamp, a wooden desk caddy and small crate for supplies, a wooden desk chair with a tied cushion, galvanized or wooden under-bed crates, a canvas hamper, a distressed-frame mirror, framed botanical and country prints, warm string lights, and a small potted herb. Keep it warm, homey and welcoming.",
    'custom': "Stage this college dorm room with the furniture and decor the user asks for, working around the fixed university-issued pieces."
  }
};
