// Tier: drift guard (public/brand/, about.html, the language packs) + island logic
// (public/scripts/brand-kit.js) — the downloadable brand kit at /about#brand-kit.
//
// The kit is the one place on the site where a FILE is the product: public/brand/ is
// generated by scripts/build-brand-kit.js from the masters in to-build/, and both the
// folder and the zip are committed. Nothing at runtime reads them, so every failure
// mode here is silent — a 404 on a download link, or a zip that is missing the file
// somebody came for because a master changed and the script was not rerun. Hence the
// guards below, which are the same shape as the i18n drift tests: they compare the
// committed artifact against its source and fail the deploy on a mismatch.
//
// The palette guard is the second half of the rule test/frontend/css-tokens.test.js
// enforces for stylesheets. That test keeps hexes out of the SHEETS; this one keeps
// the hexes printed as TEXT on the about page honest, because a swatch that says
// #2563eb while the site paints #1d4ed8 hands a journalist the wrong colour and no
// automated check would otherwise notice.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { KIT_FILES, PALETTE_TOKENS, ZIP_NAME, readPalette } from '../../scripts/build-brand-kit.js';
import { listZipEntries } from '../../scripts/zip-archive.js';
import { formatMessage, initBrandKit } from '../../public/scripts/brand-kit.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const PUB = path.join(ROOT, 'public');
const BRAND_DIR = path.join(PUB, 'brand');
const ABOUT = fs.readFileSync(path.join(PUB, 'about.html'), 'utf8');

/** The `<section id="brand-kit">` markup, so a stray match elsewhere on the page cannot pass. */
const SECTION = (() => {
  const start = ABOUT.indexOf('<section class="about__card" id="brand-kit">');
  assert.ok(start >= 0, 'about.html no longer has a #brand-kit section');
  const end = ABOUT.indexOf('</section>', start);
  return ABOUT.slice(start, end);
})();

// ── the committed artifact matches its source ──────────────────────────────────

test('every file the build script declares is present in public/brand/', () => {
  for (const [name, src] of Object.entries(KIT_FILES)) {
    const published = path.join(BRAND_DIR, name);
    assert.ok(fs.existsSync(published), `public/brand/${name} is missing — run node scripts/build-brand-kit.js`);
    assert.deepEqual(
      fs.readFileSync(published),
      fs.readFileSync(path.join(ROOT, src)),
      `public/brand/${name} differs from its master ${src} — run node scripts/build-brand-kit.js`,
    );
  }
});

test('the committed zip holds exactly what is in public/brand/', () => {
  // Set equality in both directions: a master added to KIT_FILES but never packed is
  // as broken as a file left in the zip after being dropped from the kit.
  const onDisk = fs.readdirSync(BRAND_DIR).filter((f) => f !== ZIP_NAME).sort();
  const zip = fs.readFileSync(path.join(BRAND_DIR, ZIP_NAME));
  assert.deepEqual(
    listZipEntries(zip).sort(),
    onDisk,
    `${ZIP_NAME} is out of date — run node scripts/build-brand-kit.js`,
  );
  assert.ok(onDisk.includes('README.txt'), 'the kit ships its usage guidance as README.txt');
});

test('every file in the kit is reachable from the about page, not just from the zip', () => {
  // The section grew from six pills to a product-mark grid plus a downloads row, and
  // the point of that grid is that somebody writing about Stagify+ can take the gold
  // field without unpacking the archive. A master added to KIT_FILES but never linked
  // is a file only the zip knows about — which is exactly the state the grid replaced.
  const linked = new Set([...SECTION.matchAll(/href="brand\/([^"]+)"/g)].map((m) => m[1]));
  for (const name of Object.keys(KIT_FILES)) {
    assert.ok(linked.has(name), `public/brand/${name} is in the kit but nothing on /about links it`);
  }
});

test('every download link on the about page resolves to a file', () => {
  const hrefs = [...SECTION.matchAll(/href="(brand\/[^"]+)"/g)].map((m) => m[1]);
  assert.ok(hrefs.length >= 2, 'expected the about page to link the kit');
  for (const href of hrefs) {
    assert.ok(fs.existsSync(path.join(PUB, href)), `about.html links ${href}, which does not exist`);
  }
  assert.ok(hrefs.includes(`brand/${ZIP_NAME}`), 'the whole-kit zip is the link that matters most');
  // `download` forces a save rather than letting the browser render the PNG in place.
  for (const [, tag] of SECTION.matchAll(/(<a [^>]*href="brand\/[^"]+"[^>]*>)/g)) {
    assert.match(tag, /\bdownload\b/, `missing the download attribute: ${tag}`);
  }
});

// ── the swatches tell the truth ────────────────────────────────────────────────

test('every swatch hex matches the token it claims, as defined in styles.css', () => {
  const palette = readPalette();
  const swatches = [...SECTION.matchAll(
    /data-copy="(#[0-9a-f]{6})"\s+style="--swatch:var\((--[\w-]+)\)"/g,
  )];
  assert.equal(
    swatches.length,
    Object.keys(PALETTE_TOKENS).length,
    'the swatch list and PALETTE_TOKENS in scripts/build-brand-kit.js have diverged',
  );

  for (const [, hex, token] of swatches) {
    assert.ok(token in PALETTE_TOKENS, `${token} is shown on /about but is not part of the kit's palette`);
    assert.equal(hex, palette[token], `the swatch for ${token} shows ${hex}, but styles.css defines ${palette[token]}`);
  }

  // The visible label must agree with the value the button copies: they are two
  // separate strings in the markup, and only one of them is what gets pasted.
  for (const [, copied, shown] of SECTION.matchAll(
    /data-copy="(#[0-9a-f]{6})"[\s\S]*?brand-swatch__hex">(#[0-9a-f]{6})</g,
  )) {
    assert.equal(shown, copied, 'a swatch displays a different hex than it copies');
  }
});

test('every swatch name is translated, and keyed to the colour it labels', () => {
  // The names were English-only at first, so ten locales read a Spanish page with
  // "Brand blue / Strong blue / Navy" in it. The pairing is checked as well as the
  // presence: reordering the list without moving the data-lang key with it would put
  // the right words on the wrong colour, which no amount of translation would catch.
  const EXPECTED = {
    '--brand': 'brand',
    '--brand-strong': 'strong',
    '--brand-deep': 'navy',
    '--brand-soft': 'soft',
    '--brand-pale': 'pale',
    '--brand-tint': 'tint',
    '--brand-wash': 'wash',
    '--slate': 'slate',
    '--text-heading': 'ink',
  };

  const pairs = [...SECTION.matchAll(
    /style="--swatch:var\((--[\w-]+)\)"[\s\S]*?brand-swatch__name" data-lang="about\.brand\.colors\.(\w+)"/g,
  )].map(([, token, key]) => [token, key]);
  assert.deepEqual(Object.fromEntries(pairs), EXPECTED, 'a swatch is labelled with another colour\'s key');

  const dir = path.join(PUB, 'languages');
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.json'))) {
    const colors = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')).about?.brand?.colors;
    assert.ok(colors, `${file} has no about.brand.colors block`);
    assert.deepEqual(
      Object.keys(colors).sort(),
      Object.values(EXPECTED).sort(),
      `${file}: about.brand.colors does not cover the six swatches`,
    );
  }
});

// ── the strings exist in all eleven packs ──────────────────────────────────────

test('about.brand is translated in every language pack', () => {
  // Same reason as test/i18n/unstageable-i18n.test.js: these strings have no English
  // fallback path that is visible in review, so a forgotten pack ships raw keys.
  const dir = path.join(PUB, 'languages');
  const packs = fs.readdirSync(dir).filter((f) => f.endsWith('.json'));
  assert.equal(packs.length, 11, 'expected the eleven language packs');

  const english = JSON.parse(fs.readFileSync(path.join(dir, 'english.json'), 'utf8'));
  const keys = Object.keys(english.about.brand);
  // Every key the markup asks for must be one the packs actually carry.
  for (const [, key] of SECTION.matchAll(/data-lang(?:-html)?="about\.brand\.([\w]+)"/g)) {
    assert.ok(keys.includes(key), `about.html uses about.brand.${key}, which english.json does not define`);
  }

  for (const file of packs) {
    const brand = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')).about?.brand;
    assert.ok(brand, `${file} has no about.brand block`);
    assert.deepEqual(Object.keys(brand).sort(), [...keys].sort(), `${file}: about.brand keys differ from english.json`);
    for (const k of ['copied', 'copyFailed']) {
      assert.ok(brand[k].includes('{hex}'), `${file}: about.brand.${k} must keep the {hex} placeholder`);
    }
  }
});

// ── the module ─────────────────────────────────────────────────────────────────

/**
 * The smallest shim the module touches: a list that records its click handler, and a
 * button whose closest() answers for itself.
 */
function shim({ ok = 'Copied {hex} to the clipboard', fail = 'No clipboard — {hex}' } = {}) {
  /** @type {(event: any) => void} */
  let handler = () => {};
  const button = { dataset: { copy: '#2563eb' }, closest: (sel) => (sel === '.brand-swatch' ? button : null) };
  const doc = {
    querySelector: (sel) => {
      if (sel === '[data-brand-swatches]') return { addEventListener: (_t, fn) => { handler = fn; } };
      if (sel === '[data-brand-copy-ok]') return ok === null ? null : { textContent: ok };
      if (sel === '[data-brand-copy-fail]') return fail === null ? null : { textContent: fail };
      return null;
    },
  };
  return { doc, button, click: (target) => handler({ target }) };
}

test('clicking a swatch copies its hex and says so, in the page language', async () => {
  const { doc, button, click } = shim({ ok: 'Copié {hex} !' });
  /** @type {string[]} */
  const copied = [];
  /** @type {[string, string|undefined][]} */
  const toasts = [];

  assert.equal(initBrandKit({
    doc: /** @type {any} */ (doc),
    copy: async (t) => { copied.push(t); return true; },
    toast: (m, type) => toasts.push([m, type]),
  }), true);

  click(button);
  await Promise.resolve();
  await Promise.resolve();

  assert.deepEqual(copied, ['#2563eb']);
  assert.deepEqual(toasts, [['Copié #2563eb !', 'success']]);
});

test('a refused clipboard is reported as an error, with the hex to copy by hand', async () => {
  // copyText resolves false rather than throwing when the clipboard is unreachable —
  // the whole reason it returns a boolean. Claiming success here would leave the user
  // pasting whatever was on their clipboard before.
  const { doc, button, click } = shim();
  /** @type {[string, string|undefined][]} */
  const toasts = [];

  initBrandKit({
    doc: /** @type {any} */ (doc),
    copy: async () => false,
    toast: (m, type) => toasts.push([m, type]),
  });

  click(button);
  await Promise.resolve();
  await Promise.resolve();

  assert.deepEqual(toasts, [['No clipboard — #2563eb', 'error']]);
});

test('a click that is not on a swatch is ignored', () => {
  const { doc, click } = shim();
  let copies = 0;
  initBrandKit({
    doc: /** @type {any} */ (doc),
    copy: async () => { copies++; return true; },
    toast: () => {},
  });

  click({ closest: () => null });   // the gap between two swatches
  click({});                        // a target with no closest() at all
  click(null);                      // a synthetic event with no target
  assert.equal(copies, 0);
});

test('a missing or untranslated message element degrades to the bare hex', () => {
  // language-loader.js may not have run yet, and the spans could be dropped from the
  // markup by a future edit. Neither should produce the string "undefined".
  assert.equal(formatMessage(undefined, '#2563eb'), '#2563eb');
  assert.equal(formatMessage('   ', '#2563eb'), '#2563eb');
  assert.equal(formatMessage('Copied {hex}', '#2563eb'), 'Copied #2563eb');
});

test('initBrandKit is a no-op on a page without the swatch list', () => {
  // brand-kit.js is only loaded by about.html today, but it self-starts on import.
  assert.equal(initBrandKit({ doc: /** @type {any} */ ({ querySelector: () => null }) }), false);
});
